tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  vm:
    derived_from: tosca.nodes.Compute
    properties:
      os:
        type: string
      vm_image_size:
        type: string
      vm_ram_mb:
        type: string
      vm_vcpus:
        type: string    
    interfaces:
      Standard:
        operations:
          create: 
            inputs:
              os:              { value: { get_property: [ SELF, os             ] }, type: string }
              vm_image_size:   { value: { get_property: [ SELF, vm_image_size  ] }, type: string }
              vm_ram_mb:       { value: { get_property: [ SELF, vm_ram_mb      ] }, type: string }
              vm_vcpus:        { value: { get_property: [ SELF, vm_vcpus       ] }, type: string }
              
            implementation: playbooks/vm/create.yaml
          delete: playbooks/vm/delete.yaml

topology_template:
  inputs:
    os:
      type: string
      default: ubuntu22
    vm_image_size:
      type: string
      default: 50G
    vm_ram_mb:
      type: string
      default: 4096
    vm_vcpus:
      type: string
      default: 2

  node_templates:
    my-vm:
      type: vm
      properties:
        os:              { get_input: os              }
        vm_image_size:   { get_input: vm_image_size   }
        vm_ram_mb:       { get_input: vm_ram_mb       }
        vm_vcpus:        { get_input: vm_vcpus        }

#      attributes:
#        private_address: localhost
#        public_address: localhost
      

#    hello:
#      type: hello_type
#      requirements:
#        - host: my-workstation
