tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  vm:
    derived_from: tosca.nodes.Compute
    properties:
      os:
        type: string
      vm_image_size:
        type: string
      vm_ram_mb:
        type: string
      vm_vcpus:
        type: string
      vm_user:
        type: string
      vm_ssh_key:
        type: string
    interfaces:
      Standard:
        operations:
          create:
            inputs:
              os:              { value: { get_property: [ SELF, os             ] }, type: string }
              vm_image_size:   { value: { get_property: [ SELF, vm_image_size  ] }, type: string }
              vm_ram_mb:       { value: { get_property: [ SELF, vm_ram_mb      ] }, type: string }
              vm_vcpus:        { value: { get_property: [ SELF, vm_vcpus       ] }, type: string }
              vm_user:         { value: { get_property: [ SELF, vm_user        ] }, type: string }
              vm_ssh_key:      { value: { get_property: [ SELF, vm_ssh_key     ] }, type: string }
            implementation: playbooks/vm/create.yaml
          delete: playbooks/vm/delete.yaml
    artifacts:
      image22:
        type: tosca.artifacts.File
        file: playbooks/vm/images/jammy-server-cloudimg-amd64.img
      user_template:
        type: tosca.artifacts.File
        file: playbooks/vm/user-data-template.yaml.j2

  docker:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      docker_version:
        type: string
      nginx_version:
        type: string
      site_text:
        type: string
    capabilities:
      host:
        type: tosca.capabilities.Compute
#        valid_source_types: [nginx]
    interfaces:
      Standard:
        operations:
          create:
            inputs:
              docker_version:  { value: { get_property: [ SELF, docker_version ] }, type: string }
              nginx_version:   { value: { get_property: [ SELF, nginx_version  ] }, type: string }
              site_text:       { value: { get_property: [ SELF, site_text      ] }, type: string }
            implementation: playbooks/docker/create.yaml
          delete: playbooks/docker/delete.yaml
    artifacts:
      html_template:
        type: tosca.artifacts.File
        file: artifacts/index.html.j2
      dockerfile_template:
        type: tosca.artifacts.File
        file: artifacts/Dockerfile.j2


#  nginx:
#    derived_from: tosca.nodes.SoftwareComponent
#    properties:
#      nginx_version:
#        type: string
#      site_text:
#        type: string
#    requirements:
#      - host:
#          capability: tosca.capabilities.Compute
#        valid_source_types: [nginx.Site]
#    interfaces:
#      Standard:
#        operations:
#          create:
#            inputs:
#              docker_version:  { value: { get_property: [ SELF, docker_version ] }, type: string }
#            implementation: playbooks/nginx/create.yaml
#          delete: playbooks/nginx/delete.yaml



topology_template:
  inputs:
    os:
      type: string
      default: ubuntu22
    vm_image_size:
      type: string
      default: 50G
    vm_ram_mb:
      type: string
      default: 4096
    vm_vcpus:
      type: string
      default: 2
    docker_version:
      type: string
      default: 24
    nginx_version:
      type: string
      default: latest
    site_text:
      type: string
      default: Hello here!
    vm_user:
      type: string
      default: root
    ip_address:
      type: string
      default: 192.168.122.55
    vm_ssh_public_key:
      type: string
      default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKRCyB9s/+sndwY+KY7HRntF+x5LP4We34zX23y393LTkb2ECui9bJhTWgQuwp4JJzo07g9KOsL/T8ItEjaG5w6yaqoGHOd/fQ8HILp71c7xQ+aaY78ROGnmC7tLMx7kBaWk7YWv+hq5QOaDkDn23qHaS2tAci/Tt5KeSydEt3F6oJrwpwc0VcgBnSa6CyIH3CDa63oHvFzYINvUyL7jEROk1KWrHHwqa6UEMbo/l/pSxNncEiGqNuethdI7DvamyC6dkomS7KEAugvNNqBdQAP8iLF7pSI1Yea0oVU+aljaps1d+cG2Sjc+W59kFHpiGSiiVcwfhIzGgCBQNxDlKvuzmUPVAB118s4SNBbpTVB7ebYIw2IJ6HBLXY9ezNmQoz0gsNkOlBW669pU9U9JEgQdfGUXDe1Vx4j4TXXWQvt2iczIi33SpRa6MPE1mUD1qFAoLXplKtsAIwNiRn46aL+x84kAuSFF27DPhkE9dJDzR2qtKNs5AQ2KxTCUbBhbM= remote@G512LU



  node_templates:
    my-vm:
      type: vm
      properties:
        os:              { get_input: os                }
        vm_image_size:   { get_input: vm_image_size     }
        vm_ram_mb:       { get_input: vm_ram_mb         }
        vm_vcpus:        { get_input: vm_vcpus          }
        vm_user:         { get_input: vm_user           }
        vm_ssh_key:      { get_input: vm_ssh_public_key }
      attributes:
        public_address:  { get_input: ip_address        }
        private_address: { get_input: ip_address        }

    my-docker:
      type: docker
      properties:
        docker_version:  { get_input: docker_version     }
        nginx_version:   { get_input: nginx_version      }
        site_text:       { get_input: site_text          }
      requirements:
        - host: my-vm






