- hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Install docker with specific version
      shell: |
        cd ~
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh --version {{ docker_version }}

