- hosts: all
  gather_facts: false
  become: true
  vars:
    ansible_ssh_user: "{{ ssh_user }}"
    ansible_ssh_private_key_file: "{{ ssh_key_file }}"

  tasks:
    - name: Install docker with true version
      ansible.builtin.apt:
        name: docker-compose={{ docker_version }}
