- hosts: all
  gather_facts: false
  become: true
  
  tasks:
    - name: Remove files
      shell: |
        rm -f index.html Dockerfile
        
    - name: Stop container
      shell: |
        docker container stop static-nginx

    - name: Delete docker container and image
      shell: |
        docker container rm static-nginx
        docker image rm static-nginx

